export const en = {
    hello: "Hi!",
    total: "Total",
    moving: "Moving",
    idling: "Idling",
    standing: "Standing",
    passive: "Passive",
    dailySummary: "Daily Summary",
    todaysTotalKm: "Total km today",
    mostKmInVehichles: "The most driven vehicle",
    totalAlarm: "Total Alarms",
    myCars: "My Cars",
    map: "Map",
    home: "Home",
    profile: "Profile",
    reportManagement: "Report Management",
    activityReports: "Activity Reports",
    activity_summary: "Activity-Summary Report",
    activity_detail: "Activity-Detail Report",
    notifications: "Notifications",
    contact: "Contact",
    aboutUs: "About Us",
    logout: "Log Out",
    allCars: "All Cars",
    standard: "Standard",
    hybrid: "Hybrid",
    satellite: "Satellite",
    refresh: "Refresh",
    editProfile: "Edit Profile       ",
    changePassword: "Change Password",
    notification: "Notification",
    totalVehicle: "Total Vehicle",
    businessInformation: "Business Information",
    company: "Company",
    address: "Address",
    email: "E-mail",
    related: "Related",
    relatedPhone: "Related Telephone",
    fixedNumber: "Fixed Number",
    phone: "Phone",
    taxOffice: "Tax Office",
    taxNumber: "Tax Number",
    activationTimes: "Activation Times",
    plate: "Plate",
    startingAt: "Star{ i18n.t('company')} ting At",
    end: "End",
    today: "Today",
    yesterday: "Yesterday",
    lastWeek: "Last Week",
    pickDate: "Pick date",
    getReport: "Get Report",
    notSelected: "Not Selected",
    error: "Error!",
    pleasePickADate: "Please Pick a Date!",
    ok: "OK",
    selectDateRange: "Select a date range",
    replay: "Replay",
    go: "Go",
    blockage: "Blockage",
    unblockage: "Unblockage",
    lastInfo: "Last Information",
    speed: "Speed",
    parkTime: "Parking Time",
    username: "Username",
    password: "Password",
    login: "Log in",
    forgotPassword: "Forgot password",
    rememberMe: "Remember me",
    loading: "Loading...",
    vehicleTracking: "Vehicle Tracking",
    send: "Send",
    "E-posta adresinizi girin": "Please enter your e-mail address",
    startDate: "Start date",
    endDate: "End date",
    thisWeek: "This week",
    plates: "All Plates",
    confirm: "Confirm",
    cancel: "Cancel",
    totalKilometer: "Total kilometer",
    firstPosition: "First position",
    lastPosition: "Last position",
    reportGettingReady : "Report in preparation",
    thisMayTakeSometime: 'This process may take some time...',
    line: "line",
    ignition: "Ignition",
    distance: "Distance",
    date: "Date",
    success_pathOfFile: "Success, the path of the saved file is:",
    alarm: "Alarm",
    thereAreNoNotifications: "There is no notificatication here",
    street:"Street",
    firstLocation: "First location",
    lastLocation: "Last location",
    close: "Close",
    get: "Get",
    phoneReception: "Reception",
    all : "All",
    campaigns: "Campaigns",
    settings: "Settings",
    direction: "Direction",
    car: "Car",
    dot: "Dot",
    show_hide : "Show/Hide",
    satellitePower: "Satellite Power",
    veryBad: "Very bad",
    bad : "Bad",
    medium: "Medium",
    good:"Good",
    veryGood: "Very good",
    temperatureSensor: " Temperature",
    dailyKm : "Daily km",
    totalKm : "Total km",
    battery : "Battery",
    driver : "Driver",
    model : "Model",
    infoLogin: "Only Arte Takip users can use this app.",
    canbus_reports: "Canbus Reports",
    canbus_data: "Canbus Reports",
    last_diagnostic:"Last diagnostic data:",
    diagnostic_speed: "Diagnostic speed:",
    daily_distance: "Daily distance:",
    total_distance: "Total distance",
    rpm_count: "RPM:",
    fuel_percent: "Gasoline percentage",
    daily_spended_gas: "Daily fuel consumption:",
    total_spended_gas: "Total fuel consumption:",
    engine_temp: "Engine temperature:",
    car_weight: "Vehicle weight:",
    reset: "Reset",
    blocked:"Blocked",
    feedback:"Feedback",
    arteVehicleTrackingSys:"Arte Vehicle Tracking Systems",
    ignitionDate: "Last ignition:",
    chooseReport: "Choose Report",
    reports: "Reports",
    ignition_based:"Ignition Report",
    pleasePickADay:"Please pick a day",
    fuel_level:"Fuel-Level Report",
    reportDay: "Report Day",
    logoutMessage: "Are you sure you want to exit the application?",
  }