
export const tr = {
    hello: "Merhaba!",
    total: "Toplam",
    moving: "Hareketli",
    idling: "Rölanti",
    standing: "Duran",
    passive: "Pasif",
    dailySummary: "Günlük Özet",
    todaysTotalKm: "Bugünkü toplam kilometre",
    mostKmInVehichles: "En çok kilometre yapanlar",
    totalAlarm: "Toplam alarm",
    myCars: "Araçlarım",
    map: "Harita",
    home: "Ana Sayfa",
    profile: "Profil",
    reportManagement: "Rapor Yönetimi",
    activityReports: "Aktivite Raporları",
    activity_summary: "Aktivite-Özet Raporu",
    activity_detail: "Aktivite-Detay Raporu",
    notifications: "Bildirimler",
    contact: "İletişim",
    aboutUs: "Hakkımızda",
    logout: "Güvenli Çıkış",
    allCars: "Tüm Araçlar",
    standard: "Standart",
    hybrid: "Hibrit",
    satellite: "Uydu",
    refresh: "Yenile",
    editProfile: "Profili Düzenle",
    changePassword: "Şifre Değiştir",
    notification: "Bildirim",
    totalVehicle: "Toplam Araç",
    businessInformation: "Cari Bilgiler",
    company: "Şirket",
    address: "Adres",
    email: "E-posta",
    related: "İlgili",
    relatedPhone: "İlgili Cep",
    fixedNumber: "Sabit numara",
    phone: "Telefon",
    taxOffice: "Vergi Dairesi",
    taxNumber: "Vergi Numarası",
    activationTimes: "Aktivasyon Süreleri",
    plate: "Plaka",
    startingAt: "Başlangıç",
    end: "Bitiş",
    today: "Bugün",
    yesterday: "Dün",
    lastWeek: "Bu hafta",
    pickDate: "Tarih Seç",
    getReport: "Getir",
    notSelected: "Seçilmedi",
    error: "Hata!",
    pleasePickADate: "Lütfen tarih seçin!",
    ok: "Tamam",
    selectDateRange: "Lütfen tarih aralığı seçin.",
    replay: "Tekrar İzle",
    go: "Git",
    blockage: "Bloke et!",
    unblockage: "Bloke kaldır",
    lastInfo: "Son Bilgi",
    speed: "Hız",
    parkTime: "Park Süresi",
    username: "Kullanıcı adı",
    password: "Şifre",
    login: "Giriş Yap",
    forgotPassword: "Şifremi unuttum",
    rememberMe: "Beni hatırla",
    loading: "Yükleniyor...",
    vehicleTracking: "Araç Takip",
    send: "Gönder",
    "E-posta adresinizi girin": "E-posta adresinizi giriniz.",
    startDate: "Başlangıç",
    endDate: "Bitiş",
    thisWeek: "Bu hafta",
    plates: "Tüm araçlar",
    confirm: "Onayla",
    cancel: "İptal",
    totalKilometer: "Toplam kilometre",
    firstPosition: "İlk konum",
    lastPosition: "Son konum",
    reportGettingReady : "Rapor hazırlanıyor.",
    thisMayTakeSometime: 'Bu işlem biraz zaman alabilir...',
    line: "satır",
    ignition: "Kontak",
    distance: "Mesafe",
    date: "Tarih",
    success_pathOfFile: "Başarılı, kaydedilen dosyanın yolu:",
    alarm: "Alarm",
    thereAreNoNotifications: "Burada hiç bildirim yok",
    street: "Sokak",
    firstLocation: "İlk konum",
    lastLocation: "Son konum",
    close: "Kapat",
    get: "Getir",
    phoneReception: "Çekim gücü",
    all : "Tümü",
    campaigns: "Kampanyalar",
    settings: "Ayarlar",
    direction: "Yön", 
    car: "Araba",
    dot: "Nokta",
    show_hide : "Göster/Gizle",
    satellitePower: "Çekim gücü",
    veryBad: "Çok kötü",
    bad : "Kötü",
    medium: "Orta",
    good:"İyi",
    veryGood: "Çok iyi",
    temperatureSensor: "Sıcaklık",
    dailyKm : "Günlük km",
    totalKm : "Toplam km",
    battery : "Akü",
    driver : "Şoför",
    model : "Model",
    infoLogin: "Bu uygulamayı Arte Takip'den hizmet satın alanlar kullanabilir.",
    canbus_reports: "Canbus Raporları",
    canbus_data: "Canbus Verileri",
    last_diagnostic:"Son diagnostik verisi:",
    diagnostic_speed: "Diagnostik hızı:",
    daily_distance: "Günlük mesafe:",
    total_distance: "Toplam mesafe",
    rpm_count: "Devir sayısı:",
    fuel_percent: "Benzin yüzdesi:",
    daily_spended_gas: "Harcanan günlük benzin:",
    total_spended_gas: "Harcanan toplam benzin:",
    engine_temp: "Motor sıcaklığı:",
    car_weight: "Araç ağırlığı:",
    reset: "Resetle",
    blocked:"Bloke edilmiş",
    feedback:"Geri Bildirim",
    arteVehicleTrackingSys:"Arte Araç Takip Sistemleri",
    ignitionDate: "Son kontak:",
    chooseReport: "Rapor Seçin",
    reports: "Raporlar",
    ignition_based:"Kontak Bazlı Çalışma",
    pleasePickADay:"Lütfen gün seçin",
    fuel_level:"Yakıt-Seviye Raporu",
    reportDay:"Rapor günü",
    logoutMessage: "Uygulamadan çıkmak istediğinizden emin misiniz ?",

  }